version: "3.1"

services:
    app-yourls:
        image: yourls:1-fpm-alpine
        restart: always
        # ports:
        #     - 8080:80
        environment:
            YOURLS_SITE: https://l.redig.me
            YOURLS_USER_FILE: /run/secrets/yourls_admin_username
            YOURLS_PASS_FILE: /run/secrets/yourls_admin_password
            YOURLS_DB_HOST: db_yourls
            YOURLS_DB_USER_FILE: /run/secrets/yourls_mysql_db_user
            YOURLS_DB_PASS_FILE: /run/secrets/yourls_mysql_db_pass
        networks:
            - internal
            - caddy_proxy
        secrets:
            - yourls_admin_username
            - yourls_admin_password
            - yourls_mysql_db_user
            - yourls_mysql_db_pass

    db_yourls:
        image: mariadb:10.5
        restart: always
        volumes:
            - yourls_db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/yourls_mysql_root_pw
            - MYSQL_DATABASE=yourls
            - MYSQL_USER_FILE=/run/secrets/yourls_mysql_db_user
            - MYSQL_PASSWORD_FILE=/run/secrets/yourls_mysql_db_pass
        networks:
            - internal
        secrets:
            - yourls_mysql_root_pw
            - yourls_mysql_db_user
            - yourls_mysql_db_pass

secrets:
    yourls_admin_username:
        external: true
    yourls_admin_password:
        external: true
    yourls_mysql_root_pw:
        external: true
    yourls_mysql_db_user:
        external: true
    yourls_mysql_db_pass:
        external: true

networks:
    internal:
    caddy_proxy:
        external: true

volumes:
    yourls_db:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "${HOME}/.config/redig_link_shortener_config/yourls_db/"
